In [8]:
import numpy as np
ar=np.array([[[23],[22]],[[3],[55]],[[33],[44]],[[66],[77]]])
print(ar)
print("dimestion is ",ar.ndim)

[[[23]
  [22]]

 [[ 3]
  [55]]

 [[33]
  [44]]

 [[66]
  [77]]]
dimestion is  3

In [17]:
import numpy as np
arr=np.array([[33,55,44],[22,44,77],[33,22,23]])
arr.shape
D=arr.ndim
arr.size

9

In [28]:
import numpy as np
ard=np.array([
    [[[22,55,66],
     [21,34,53]],
     
     [[34,23,12],
      [53,21,34] , 
     ]
    ],
    [
        [[23,12,53],
         [43,12,34]],
        
        [[34,3,23],
        [12,31,23]]
    ]] 

)
ad=ard.ndim
print(ad," \n")
ard.shape

4

(2, 2, 2, 3)

In [32]:
import numpy as np
a=np.array(

[
    [
    [[33,44,66],
    [22,55,77]],


    [[33,55,77],
    [23,43,64]],

    ],

    [
        [[34,54,23],
         [35,12,32]
        ],
        [
            [32,12,34],
             [23,12,21]
         ]

    ]
]








)
a.ndim
a.shape

(2, 2, 2, 3)

In [36]:
arr=np.zeros((2,5,2,3))


print(arr)

[[[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]]

In [38]:
ar=np.ones((3,2,3))
print(ar)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]

In [ ]:
arr=np.empty(4)
arr
d=np.arange(0,10,2)
print(d)
ar=np.linspace(0,10, num=5)
ar
ad=np.ones((2,4),dtype=np.float16)
print(ad)

[0 2 4 6 8]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

In [64]:
arr=np.random.randint(0,10,6)
arr
np.sort(arr)

array([0, 2, 2, 3, 4, 7])

In [72]:
a=np.array([23,11,23,12,44,52])
b=np.array([23,23,11,2,12,66])
print(a+b)
c=np.concatenate((a,b), axis=0)
d=np.sort(c)

d

[ 46  34  34  14  56 118]

array([ 2, 11, 11, 12, 12, 23, 23, 23, 23, 44, 52, 66])

In [ ]:
c=np.arange(10)
c.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
import numpy as np 
ard=np.arange(0,10)
print(ard)
ard = np.reshape(ard, (2, 5))

ard

[0 1 2 3 4 5 6 7 8 9]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
ar=np.arange(0,10)
np.reshape(ar,(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [101]:
dd=np.arange(0,10)
print(dd)

print("\n")


dd=np.reshape(dd,(2,5),order='F')
print(dd)
dd=np.reshape(dd,(2,5), order='C')
dd

[0 1 2 3 4 5 6 7 8 9]


[[0 2 4 6 8]
 [1 3 5 7 9]]

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [116]:

arr=np.arange(0,10)
arr


arr[0:]
arr[4:]
arr[-3:]


print("\n")



arr[:-1]
print(arr<5)
print(arr[arr>5])
arr=a[(a<6 )|(a>9)]
arr


arr

[ True  True  True  True  True False False False False False]
[6 7 8 9]

array([23, 11, 23, 12, 44, 52])

In [132]:
ad=np.arange(60)


np.nonzero([(ad>20)&(ad<50)])


bb=np.arange(9)
print(bb)

np.reshape(bb,(3,3), order="C")

[0 1 2 3 4 5 6 7 8]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [138]:
arr=np.arange(9)
arr

arr.shape
np.ndim(arr)

dd=np.expand_dims(arr,axis=0)
np.ndim(dd)

2

In [147]:
arr=np.arange(9)
np.nonzero([(arr<8) | (arr>6)])

(array([0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 1, 2, 3, 4, 5, 6, 7, 8]))

In [150]:
a1=np.array([[23,44,55],
             [22,11,24]])
a2=np.array([[33,44,22],
            [11,33,55]])
np.vstack((a1,a2))

array([[23, 44, 55],
       [22, 11, 24],
       [33, 44, 22],
       [11, 33, 55]])

In [158]:
arrd=np.arange(64).reshape(8,8)
arrd

np.hsplit(arrd,2)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27],
        [32, 33, 34, 35],
        [40, 41, 42, 43],
        [48, 49, 50, 51],
        [56, 57, 58, 59]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31],
        [36, 37, 38, 39],
        [44, 45, 46, 47],
        [52, 53, 54, 55],
        [60, 61, 62, 63]])]

In [ ]:
import numpy as np
aa=np.arange(10).reshape(2,5)
aa[:,2].sum()
aa
aa[1].sum()


aa[0].sum()
print(aa)

np.max(aa,axis =0)
np.prod(aa,axis =1)

np.prod(aa, axis=0)
np.mean(aa)
np.std(aa)

arr=np.random.randint(1,10,(5,2))
np.transpose(arr)
arr
np.flip(arr, axis =1
        )

[[0 1 2 3 4]
 [5 6 7 8 9]]

array([[2, 7],
       [8, 9],
       [5, 8],
       [2, 5],
       [9, 5]])

In [27]:
ard=np.random.randint(1,12,(3,4))
print(ard)
dd=np.flip(ard,axis =0)
print("\n")
print(dd)

[[ 7  5 11  8]
 [ 7  3  8  7]
 [11  2  1 11]]


[[11  2  1 11]
 [ 7  3  8  7]
 [ 7  5 11  8]]

In [ ]:
import pandas as pd 
data =[23,44,55,66,67]
index =['a','b','c','d','e']
pd.Series(data,index=index)



arr=pd.DataFrame({
    "Name":["Kamal","Yash","Kashish","Dhanwani"],
    "City":["Jaipur","Rajsthan","Ajmer","LKashmeer"],
    "Class":[12,14,15,11]}
    )
arr


ad=pd.DataFrame(["Kamal","Yash","Pankaj","Kashish"],columns=["Name"],index=["c1","c2","c3","c4"],
                ["Jaipur","Ajmer","Pakistan","Jmmu"],colums=["City"])
ad

       Name
c1    Kamal
c2     Yash
c3   Pankaj
c4  Kashish

In [ ]:
import pandas as pd
arr=pd.read_csv("Student.csv")
arr
arr.head(3)
arr.tail(2)
arr.sample(2)
arr.sample(4,random_state=2)

       Name  StudentId  Class           Subject
2     Anjli          6     33           Physics
4   Carline          9     15           Chutiya
1  Dhanwani          4     21           Science
3    Muskan          7     14  Computer_Science

In [12]:
import pandas as pd
arr=pd.read_csv("Student.csv")
arr.sample(4,random_state=2)

       Name  StudentId  Class           Subject
2     Anjli          6     33           Physics
4   Carline          9     15           Chutiya
1  Dhanwani          4     21           Science
3    Muskan          7     14  Computer_Science

In [19]:
arr.columns
list(arr.index)

[0, 1, 2, 3, 4]

In [24]:
arr.shape

arr.size
arr.describe()
arr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   StudentId  5 non-null      int64
 2   Class      5 non-null      int64
 3   Subject    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [ ]:
        #loc = location based indexing

arr.loc[0,"Name"]

'Kamal'

In [27]:
arr.loc[2,"Name"]

'Anjli'

In [29]:
arr.loc[3,"Class"]

np.int64(14)

In [32]:
arr.loc[0:5,"Class"]

0    11
1    21
2    33
3    14
4    15
Name: Class, dtype: int64

In [37]:
arr.loc[0:2]
arr.loc[0:3,["Name", "Class"]]

       Name  Class
0     Kamal     11
1  Dhanwani     21
2     Anjli     33
3    Muskan     14

In [39]:
arr.loc[0:3,["Class","Subject"]]

   Class           Subject
0     11          Commerce
1     21           Science
2     33           Physics
3     14  Computer_Science

In [41]:
arr.loc[[0,2,3],["Name","Subject"]]

     Name           Subject
0   Kamal          Commerce
2   Anjli           Physics
3  Muskan  Computer_Science

In [ ]:

import pandas as pd 
arr=pd.read_csv("big_sample.csv")
arr.shape
arr.describe()


arr.head(15)
arr.tail(15)

arr.loc[2:15,"ID":"Score"]
arr.loc[[2,10,16,85]]

    ID     Name  Age     City  Score
2    3     Neha   52    Delhi     68
10  11   Pankaj   36    Delhi     62
16  17  Kashish   33   Indore     11
85  86   Pankaj   19  Kolkata     12

In [56]:
            #iloc integers location based indexing 

arr.iloc[0:10,2]
arr.iloc[0:3,0]
arr.iloc[[0,10,15],3]

0       Delhi
10      Delhi
15    Kolkata
Name: City, dtype: object

In [ ]:
arr.at[0,"Name"]
arr["Name"]

NameError: name 'arr' is not defined

NameError: name 'arr' is not defined

In [ ]:
import pandas as pd
arr=pd.read_csv("big_sample.csv")
bd=arr.head(20)
bd[bd(["Age"]>25) & bd(bd["Name"]=="Pankaj")]
bd.loc

TypeError: '>' not supported between instances of 'list' and 'int'